services:
  chance-api:
    build:
      context: .. # Path to the directory containing the Dockerfile
      dockerfile: docker/Dockerfile
    ports:
      - "10001:10001"
    volumes:
      - /home/saman/IdeaProjects/number-generator/rest-server/files:/app/files